name: Environment Variable - Secrets

on: [push]

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Access Secrets
        run: |
          echo "REACT_APP_KEY =$REACT_APP_PORTFOLIO_API_KEY" >> .env
