name: Environment Variable - Secrets

on: [push]

jobs:
  secrets-test:
    runs-on: ubuntu-latest

    steps:
      - name: Access Secrets
        run: |
          echo "REACT_APP_PORTFOLIO_API_KEY = ${{secrets.REACT_APP_PORTFOLIO_API_KEY}}" >> .env
          cat .env
          echo "REACT_APP_KEY = ${{secrets.REACT_APP_KEY}} >> .env
          cat .env

